version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: miausociau-db
    environment:
      POSTGRES_DB: miausocial
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senhasegura123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - miaunet

  springboot-app:
    build: .
    container_name: miausociau-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/miausocial
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: senhasegura123
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - miaunet

  mongodb:
    image: mongo:latest
    container_name: miausociau-mongo
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    networks:
      - miaunet

  redis:
    image: redis:latest
    container_name: miausociau-redis
    ports:
      - "6379:6379"
    networks:
      - miaunet

volumes:
  postgres_data:

networks:
  miaunet:
    driver: bridge
