spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miausocial
    username: admin
    password: senhasegura123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  springdoc:
    api-docs:
      path:
        /api-docs
    swagger-ui:
      path:
        /swagger-ui.html
