spring:
  profiles:
    default: dev
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:miausocial}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  springdoc:
    api-docs:
      path:
        /api-docs
    swagger-ui:
      path:
        /swagger-ui.html
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ${MONGO_INITDB_DATABASE:miaudb}
      username: ${MONGO_ROOT_USERNAME:root}
      password: ${MONGO_ROOT_PASSWORD:secret}
      authentication-database: admin

  redis:
    host: redis
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

server:
  port: 8080
  tomcat:
    max-threads: 200
    max-connections: 10000
    accept-count: 100
    connection-timeout: 5000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    br.com.miausocial: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure-in-production}
  expiration: 86400000
