spring:
  profiles:
    default: dev
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/miausocial
    username: admin
    password: senhasegura123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  springdoc:
    api-docs:
      path:
        /api-docs
    swagger-ui:
      path:
        /swagger-ui.html
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: mydatabase
      username: root
      password: secret
      authentication-database: admin
  redis:
    host: redis
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
